"""new relations added

Revision ID: 584d8f013093
Revises: 8a7490154868
Create Date: 2019-01-06 13:54:10.787651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584d8f013093'
down_revision = '8a7490154868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('victimType', sa.String(length=255), nullable=True),
    sa.Column('victimName', sa.String(length=255), nullable=True),
    sa.Column('perpetratorName', sa.String(length=255), nullable=True),
    sa.Column('reporterName', sa.String(length=255), nullable=True),
    sa.Column('reporterPhone', sa.String(length=255), nullable=True),
    sa.Column('detailsCrime', sa.String(length=1250), nullable=True),
    sa.Column('detailsPlace', sa.String(length=1250), nullable=True),
    sa.Column('county', sa.String(length=255), nullable=True),
    sa.Column('constituency', sa.String(length=255), nullable=True),
    sa.Column('urgency', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('assignedOrganization', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('stage', sa.String(length=255), nullable=True),
    sa.Column('files', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.LargeBinary(), nullable=True),
    sa.Column('webURL', sa.String(length=255), nullable=True),
    sa.Column('orgBrief', sa.String(length=255), nullable=True),
    sa.Column('founded', sa.DateTime(), nullable=True),
    sa.Column('registered', sa.DateTime(), nullable=True),
    sa.Column('alertCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Type', sa.String(length=255), nullable=True),
    sa.Column('personName', sa.String(length=255), nullable=True),
    sa.Column('identification', sa.String(length=255), nullable=True),
    sa.Column('DOB', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('phoneNo1', sa.String(length=255), nullable=True),
    sa.Column('phoneNo2', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('caseCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staffFirstName', sa.String(length=255), nullable=True),
    sa.Column('staffSecondName', sa.String(length=255), nullable=True),
    sa.Column('staffLastName', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('staffDesignation', sa.String(length=255), nullable=True),
    sa.Column('identification', sa.String(length=255), nullable=True),
    sa.Column('DOB', sa.DateTime(), nullable=True),
    sa.Column('photo', sa.LargeBinary(), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('phoneNo1', sa.String(length=255), nullable=True),
    sa.Column('phoneNo2', sa.String(length=255), nullable=True),
    sa.Column('caseCount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Alert', sa.Column('choiceOrganization', sa.String(length=255), nullable=True))
    op.add_column('Alert', sa.Column('detailsCrime', sa.String(length=1250), nullable=True))
    op.add_column('Alert', sa.Column('detailsPlace', sa.String(length=1250), nullable=True))
    op.add_column('Alert', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('Alert', sa.Column('perpetratorName', sa.String(length=255), nullable=True))
    op.add_column('Alert', sa.Column('reporterPhone', sa.String(length=255), nullable=True))
    op.add_column('Alert', sa.Column('urgency', sa.String(length=255), nullable=True))
    op.drop_column('Alert', 'details')
    op.drop_column('Alert', 'reporterEmail')
    op.add_column('User', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'name')
    op.add_column('Alert', sa.Column('reporterEmail', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('Alert', sa.Column('details', sa.VARCHAR(length=1250), autoincrement=False, nullable=True))
    op.drop_column('Alert', 'urgency')
    op.drop_column('Alert', 'reporterPhone')
    op.drop_column('Alert', 'perpetratorName')
    op.drop_column('Alert', 'location')
    op.drop_column('Alert', 'detailsPlace')
    op.drop_column('Alert', 'detailsCrime')
    op.drop_column('Alert', 'choiceOrganization')
    op.drop_table('Staff')
    op.drop_table('Person')
    op.drop_table('Organization')
    op.drop_table('Case')
    # ### end Alembic commands ###
