"""MINOR CHANGES

Revision ID: 69e336c86df9
Revises: 3498ce6d915a
Create Date: 2019-01-08 11:31:51.001907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e336c86df9'
down_revision = '3498ce6d915a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Alert', sa.Column('ward', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Alert', 'ward')
    # ### end Alembic commands ###
