"""modified Alert table

Revision ID: 8a7490154868
Revises: ec29ee52de82
Create Date: 2018-08-31 17:54:32.905363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8a7490154868'
down_revision = 'ec29ee52de82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Alert', sa.Column('time', sa.DateTime(), nullable=True))
    op.drop_column('Alert', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Alert', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Alert', 'time')
    # ### end Alembic commands ###
