"""empty message

Revision ID: 9b367c131df2
Revises: ad36a22eba75
Create Date: 2019-03-16 10:59:36.525826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b367c131df2'
down_revision = 'ad36a22eba75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Alert', 'choiceOrganization')
    op.add_column('User', sa.Column('org_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'User', 'Organization', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_column('User', 'org_id')
    op.add_column('Alert', sa.Column('choiceOrganization', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
