"""empty message

Revision ID: ad36a22eba75
Revises: 90b1f1676d8b
Create Date: 2019-03-16 10:32:26.841747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad36a22eba75'
down_revision = '90b1f1676d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Alert', sa.Column('org_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Alert', 'Organization', ['org_id'], ['id'])
    op.drop_column('Case', 'files')
    op.drop_column('Organization', 'logo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Organization', sa.Column('logo', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('Case', sa.Column('files', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Alert', type_='foreignkey')
    op.drop_column('Alert', 'org_id')
    # ### end Alembic commands ###
