"""'Initial'

Revision ID: ec29ee52de82
Revises: 
Create Date: 2018-08-31 07:38:51.659047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec29ee52de82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Alert', sa.Column('details', sa.String(length=1250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Alert', 'details')
    # ### end Alembic commands ###
